title: Field notes from a security engineer
description: A collection of technical notes scoped to Microsoft security platforms from a security engineer's perspective.
remote_theme: minima
markdown: kramdown

header_pages:
  - index.md
  - about.md